name: 05- CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs: 
  ci: 
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      
      - name: Preparar pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11
          run_install: false
      
      - name: Install dependecies
        run: | 
          cd 12-ejercicio-cicd
          echo "::group::Instalar dependecias"
          pnpm install --frozen-lockfile
          echo "::endgroup::"

      - name: Lint
        run: | 
          cd 12-ejercicio-cicd
          echo "::group::Lint"
          pnpm run lint
          echo "::endgroup::"

      - name: Test
        run: | 
          cd 12-ejercicio-cicd
          echo "::group::Test"
          pnpm run test
          echo "::endgroup::"

      - name: Build 
        run: | 
          cd 12-ejercicio-cicd
          echo "::group::Build"
          pnpm run build
          echo "::endgroup::"

      