name: 05- CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

# Esto es una buena práctica y hasta algo más cómodo para no tener que hacer `cd 12-ejercicio-cicd` en cada paso
defaults:
    run:
        working-directory: 12-ejercicio-cicd

jobs: 
  frontend-lint: 
    runs-on: ubuntu-24.04

    steps:
     
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-pnpm-ci-cd
      - name: Lint
        run: | 
          echo "::group::Lint"
          pnpm lint:frontend
          echo "::endgroup::"
         
          
          
  frontend-test:
    runs-on: ubuntu-24.04
    steps:
     - uses: actions/checkout@v6
     - uses: ./.github/actions/setup-pnpm-ci-cd
     - name: Test
       run: | 
          echo "::group::Test"
          pnpm test:frontend
          echo "::endgroup::"

  frontend-build:
      needs: [frontend-lint, frontend-test]
      runs-on: ubuntu-24.04
      steps:
        - uses: actions/checkout@v6
        - uses: ./.github/actions/setup-pnpm-ci-cd
        - name: Build
          run: |
            echo "::group::Build"
            pnpm build:frontend
            echo "::endgroup::"

     
  backend-lint: 
     runs-on: ubuntu-24.04
     steps:
       - uses: actions/checkout@v6
       - uses: ./.github/actions/setup-pnpm-ci-cd
       - name: Lint
         run: |
           echo "::group::Lint"
           pnpm lint:backend
           echo "::endgroup::" 

  backend-test:
     runs-on: ubuntu-24.04
     steps:
       - uses: actions/checkout@v6
       - uses: ./.github/actions/setup-pnpm-ci-cd
       - name: Test
         run: |
           echo "::group::Test"
           pnpm test:backend
           echo "::endgroup::"
         
      
  backend-build:
      needs: [backend-lint, backend-test]
      runs-on: ubuntu-24.04
      steps:
          - uses: actions/checkout@v6
          - uses: ./.github/actions/setup-pnpm-ci-cd
          - name: Build
            run: |
              echo "::group::Build"
              pnpm build:backend
              echo "::endgroup::"

